title: Minjie Fu # your name (or website title) here
logo: "/images/logods.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with over 7 years of experience in analytics and modeling in the financial and consulting industries. 
  Holder of a CPA license, a Master's degree in Computer Science from UIUC, and an MBA from SBU. 
  
  
  <br><br>
  Proficient in financial performance prediction, budgeting, risk management, fraud detection, causal inference, and customer behavior analysis. 
  Key clients include KFC, Pizza Hut, Dunkin' Donuts, and FIAT Auto. 
  Experienced in big data technologies, NLP, AWS, and cross-functional collaboration.
  <br><br>
  <a href="https://www.linkedin.com/in/minjiefu/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
